webpack_encore:
    output_path: '%kernel.project_dir%/public/default_build'
    builds:
        nrjConfig: '%kernel.project_dir%/public/nrj/build'
        nostalgieConfig: '%kernel.project_dir%/public/nostalgie/build'
